---
title: "Q3"
output: html_notebook
---
*requirements*
```{r setup, include=FALSE}
library(rgl)
#library(rglwidget) #does not show any pictures in Rmarkdown if rglwidget()  is called after rgl
setupKnitr()
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message=FALSE,
                      webgl = TRUE,
                      dpi=100,
                      fig.width = 7, 
                      fig.height = 7,
                      fig.align='left',rgl.closewindows=TRUE
                      )
require(Umatrix)
require(FCPS)
require(DataVisualizations)
require(ProjectionBasedClustering)
require(GeneralizedUmatrix)
require(stats)
require(caret)
knitr::knit_hooks$set(webgl = hook_webgl)
```


*Import data*

```{r}

file_path <- "WisconsinDiagnosislrn.sec"
data <- read.table(file_path, sep = "\t", header = FALSE, comment.char = "%", skip = 1)

column_names <- c("Key", "Mean_radius", "Mean_texture", "Mean_perimeter", "Mean_area", "Mean_smoothness", "Mean_compactness", "Mean_concavity", "Mean_concave_points", "Mean_symmetry", "Mean_fractal_dimension", 
                  "SE_radius", "SE_texture", "SE_perimeter", "SE_area", "SE_smoothness", "SE_compactness", "SE_concavity", "SE_concave_points", "SE_symmetry", "SE_fractal_dimension", 
                  "Worst_radius", "Worst_texture", "Worst_perimeter", "Worst_area", "Worst_smoothness", "Worst_compactness", "Worst_concavity", "Worst_concave_points", "Worst_symmetry", "Worst_fractal_dimension")
colnames(data) <- column_names

head(data)


```


```{r}
file_path <- "WisconsinDiagnosis.cls"
classes <- read.table(file_path, comment.char = "#", sep = "\t", header = FALSE)
classes <- classes[!grepl("^%", classes$V1), ]
colnames(classes) <- c("key", "Class")
head(classes)
```


*Scaling and other preprocessing* 
```{r}

normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

data.nr <- as.data.frame(lapply(data, function(x) {
  if (is.numeric(x)) {
    return(normalize(x))
  } else {
    return(x)
  }
}))

data.nr = as.matrix(data.nr)
data.sc = scale(data)

pca_result <- prcomp(data[, -1], scale. = TRUE)
pca_transformed_data <- pca_result$x
data.pca <- as.matrix(cbind(data[, 1], pca_transformed_data))

data.current <- data.nr
```



```{r}
MDplot(data.current)+ggplot2::ggtitle(
  'Is this a appropriate normalizations?')

cc=cor(data.current)
diag(cc)=0
DataVisualizations::Pixelmatrix(cc,
      main = 'Pearson Correlation')
```


```{r}
OtherDistance=as.matrix(parallelDist::parallelDist(
  data.current,method = 'geodesic')
  )
OutputDim=50
Trans=ProjectionBasedClustering::MDS(
  DataOrDistances = OtherDistance,
  OutputDimension = OutputDim)$ProjectedPoints

DataVisualizations::Sheparddiagram(OtherDistance,
  as.matrix(dist(Trans)),main = 
  'Decide if relationship between distances is appropriate'
  )

V=DataVisualizations::ShepardDensityScatter(OtherDistance,
  as.matrix(dist(Trans)),main = 
  'Decide if relationship between distances is appropriate'
  )
```


```{r}
high_cor_features <- findCorrelation(cc, cutoff = 0.75)
data.without_correlated <- data.current[, -high_cor_features]
data.without_correlated <- data.without_correlated[,-1]
```

```{r}
MDplot(data.without_correlated)+ggplot2::ggtitle(
  'Is this a appropriate normalizations?')

cc=cor(data.without_correlated)
diag(cc)=0
DataVisualizations::Pixelmatrix(cc,
      main = 'Pearson Correlation')
```

```{r}
OtherDistance=as.matrix(parallelDist::parallelDist(
  data.without_correlated,method = 'geodesic')
  )
OutputDim=50
Trans=ProjectionBasedClustering::MDS(
  DataOrDistances = OtherDistance,
  OutputDimension = OutputDim)$ProjectedPoints

DataVisualizations::Sheparddiagram(OtherDistance,
  as.matrix(dist(Trans)),main = 
  'Decide if relationship between distances is appropriate'
  )

V=DataVisualizations::ShepardDensityScatter(OtherDistance,
  as.matrix(dist(Trans)),main = 
  'Decide if relationship between distances is appropriate'
  )
```


```{r include=FALSE}

res = esomTrain(Data = data.pca,
                Lines = 60,
                Columns = 80,
                Epochs = 1000,
                Toroid = T,
                NeighbourhoodFunction = "cone",
                StartLearningRate = 0.9,
                EndLearningRate = 0.01,
                StartRadius = 30,
                EndRadius = 2,
                NeighbourhoodCooling = "Lead In Lead Out",
                LearningRateCooling = "Lead In Lead Out",
                Key = data[,1],
                UmatrixForEsom = T)

```
```{r}
ggobj=ProjectionBasedClustering::PlotProjectedPoints(
  res$BestMatches[,-1],
  Cls = classes$Class,
  BMUorProjected = T,
  main = 'Plot of Neural map, marked are BMUs')
```

```{r, message=FALSE, webgl=TRUE}
UmatrixInformation = Umatrix::umatrixForEsom(
  res$Weights, 
  Columns = res$Columns,
  Lines = res$Lines,
  Toroid = T
)

GeneralizedUmatrix::plotTopographicMap(UmatrixInformation,
                                       res$BestMatches,
                                       Cls = classes$Class,
                                       Toroid = T

)
```



```{r}
Pmatrix = pmatrixForEsom(data.pca,
                         res$Weights,
                         res$Lines,
                         res$Columns,
                         res$Toroid)

plotMatrix(Pmatrix, ColorStyle = "Pmatrix", Toroid = T)

```



```{r}
Ustarmatrix = ustarmatrixCalc(res$Umatrix, Pmatrix)
plotMatrix(res$Umatrix, Cls = classes$Class, res$BestMatches, Toroid = T)
```



```{r}
cls = iClassification(res$Umatrix, res$BestMatches)
```

```{r}
head(data.current)
```


